name        : quasselclient
version     : 0.12.3
release     : 1
source     :
    - http://quassel-irc.org/pub/quassel-0.12.3.tar.bz2 : 4d3ee91b85cce3d8df62faf55ad35bebd6fc45085ed6248b8a41d2858de3d434
license     :
    - GPL-3.0
    - GPL-2.0
summary     : The Quassel IRC Client without the core (server-component)
description : |
  Quassel IRC is a modern, cross-platform, distributed IRC client based on the Qt4 framework.
  Distributed means that one (or multiple) client(s) can attach to and detach from a central core that stays permanently online -- much like the popular combination of screen and a text-based IRC client such as WeeChat, and similar to (but much more featureful than) so-called BNCs. Re-attaching your client will show your IRC session in the same state as you left it in (plus whatever happened while you were gone), and this even when you re-attach from a different location. In addition, Quassel IRC can be used like a traditional client, with providing both client and core functionality in one binary. This so-called "Monolithic Client" completely hides the distributed nature, so for a purely local installation, Quassel IRC can be setup very easily.
  Cross-platform means that Quassel IRC is developed for and tested on Linux®, Windows®, and MacOS X®. It should also run on any other platform that is supported by Digia's Qt4 library. Third-party mobile clients for Android and iOS also exist.
  By modern we mean that Quassel IRC will have all the features you'd expect from an IRC client nowadays. It also innovates in many areas. For example, the GUI features a dockable nicklist and topic bar, or you can arrange your channel and query buffers in default or custom views, which are also dockable. This means that you can arrange your GUI as you please. The architecture allows for other innovations, such as on-demand creation of log files in custom formats from the backlog.
  The Quassel IRC Team
  The core development team currently consists of the following people:
  Manuel "Sputnick" Nickschas
  Marcus "EgS" Eggenberger
  Many more people have contributed ideas, patches, testing and other stuff; they're listed in the "About" dialog of the Quassel client. Thanks to everybody helping to make Quassel IRC a kick-ass program!
clang: yes
builddeps:
  - pkgconfig(Qt5Core)
  - pkgconfig(gl)
setup      : |
    %cmake -DWANT_QTCLIENT=ON -DWANT_CORE=OFF -DWANT_MONO=OFF -DUSE_QT5=ON -DWITH_KDE=OFF -DWITH_OXYGEN=ON -DWITH_WEBKIT=OFF -DEMBED_DATA=OFF
build      : |
    %make
install    : |
    %make_install
